name: event-bus
path: git::https://github.com/awslabs/aiops-modules.git//modules/examples/event-bus?ref=release/1.7.0&depth=1
targetAccount: tooling
parameters:
  - name: event_bus_name
    value: mlops-bus
  - name: source_accounts
    value: '["123123123123"]'  # Accounts that must have permissions to put events (source accounts)
  - name: tags
    value: '{"test": "test"}'
