name: model-pipeline
path: git::https://github.com/awslabs/aiops-modules.git//modules/sagemaker/sagemaker-model-package-promote-pipeline?ref=release/3.2.0&depth=1
targetAccount: tooling
parameters:
  - name: source_model_package_group_arn
    valueFrom:
      moduleMetadata:
        group: registry
        name: source-model-package-group
        key: SagemakerModelPackageGroupArn
  - name: target_bucket_name
    value: my-bucket-name
  - name: event_bus_name
    valueFrom:
      moduleMetadata:
        group: events
        name: event-bus
        key: EventBusName
  - name: target_model_package_group_name
    valueFrom:
      moduleMetadata:
        group: registry
        name: target-model-package-group
        key: SagemakerModelPackageGroupName
