name: networking
path: git::https://github.com/awslabs/idf-modules.git//modules/network/basic-cdk?ref=release/1.7.0&depth=1
targetAccount: primary
parameters:
  - name: internet-accessible
    value: True
---
name: networking-secondary
path: git::https://github.com/awslabs/idf-modules.git//modules/network/basic-cdk?ref=release/1.3.0&depth=1
targetAccount: secondary
parameters:
  - name: internet-accessible
    value: True