name: networking-dev
path: git::https://github.com/awslabs/idf-modules.git//modules/network/basic-cdk?ref=release/1.3.0&depth=1
targetAccount: dev
parameters:
  - name: internet-accessible
    value: True
---
name: networking-pre-prod
path: git::https://github.com/awslabs/idf-modules.git//modules/network/basic-cdk?ref=release/1.3.0&depth=1
targetAccount: pre-prod
parameters:
  - name: internet-accessible
    value: True
---
name: networking-prod
path: git::https://github.com/awslabs/idf-modules.git//modules/network/basic-cdk?ref=release/1.3.0&depth=1
targetAccount: prod
parameters:
  - name: internet-accessible
    value: True
