name: lustre-on-eks
# path: git::https://github.com/srinivasreddych/idf-modules.git//modules/integration/fsx-lustre-on-eks?ref=release/1.9.0
path: git::https://github.com/srinivasreddych/idf-modules.git//modules/integration/fsx-lustre-on-eks?ref=feat/karpenter
parameters:
  - name: EksClusterAdminRoleArn
    valueFrom:
      moduleMetadata:
        group: core
        name: eks
        key: EksClusterMasterRoleArn
  - name: EksHandlerRoleArn
    valueFrom:
      moduleMetadata:
        group: core
        name: eks
        key: EksHandlerRoleArn
  - name: EksClusterName
    valueFrom:
      moduleMetadata:
        group: core
        name: eks
        key: EksClusterName
  - name: EksOidcArn
    valueFrom:
      moduleMetadata:
        group: core
        name: eks
        key: EksOidcArn
  - name: EksClusterSecurityGroupId
    valueFrom:
      moduleMetadata:
        group: core
        name: eks
        key: EksClusterSecurityGroupId
  - name: Namespace
    valueFrom:
      parameterValue: rayNamespaceName
  - name: FsxFileSystemId
    valueFrom:
      moduleMetadata:
        group: core
        name: fsx-lustre
        key: FSxLustreFileSystemId
  - name: FsxSecurityGroupId
    valueFrom:
      moduleMetadata:
        group: core
        name: fsx-lustre
        key: FSxLustreSecurityGroup
  - name: FsxMountName
    valueFrom:
      moduleMetadata:
        group: core
        name: fsx-lustre
        key: FSxLustreMountName
  - name: FsxDnsName
    valueFrom:
      moduleMetadata:
        group: core
        name: fsx-lustre
        key: FSxLustreAttrDnsName
  - name: DraExportPath
    valueFrom:
      parameterValue: draExportPath
