name: Check One-Click Launch Template

on:
  push:
    branches:
      - "main"
    paths:
      - "one-click-launch.yaml"
      - "requirements-dev.txt"
      - ".github/workflows/one-click-template-lint.yml"

  pull_request:
    branches:
      - "main"
      - "release/*"
      - "stable"
    paths:
      - "one-click-launch.yaml"
      - "requirements-dev.txt"
      - ".github/workflows/one-click-template-lint.yml"

permissions:
  contents: read
  security-events: write

jobs:
  lint:
    name: CFN Lint Template
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Set up Python
        run: uv python install 3.11
      - name: Install Requirements
        run: |
          set -x
          uv pip install --system -r requirements-dev.txt
      - name: cfn-lint
        run: cfn-lint --template ./one-click-launch.yaml

  nag:
    name: CFN Nag Template
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: cfn-nag
        uses: stelligent/cfn_nag@master
        with:
          input_path: ./one-click-launch.yaml
          extra_args: -o sarif
          output_path: cfn_nag.sarif
      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: cfn_nag.sarif
